stages:
  - build
  - deploy
  - test

build1:
  stage: build
  script:
      - echo "Do your build here" >/tmp/build.txt
  tags:
      - build
test1:
  stage: test
  script:
    - echo "test-1" /tmp/test1.txt
  tags:
      - test

test2:
  stage: test
  script:
    - echo "Do another parallel test here" >/tmp/test2.txt
  tags:
      - test

deploy1:
  stage: deploy
  only:
    - master
  script:
    - echo "Do your deploy here" >/tmp/deploy.txt
  tags:
      - deploy
